### ISSUE TITLE
Move away from deprecated `harfbuzz._shape` method

### ISSUE THREAD

**Issue by deepakjois** [michal-h21/luaharfbuzz-luatex-test#1]
Two things need to be done
- Use `require 'harfbuzz'` instead of `require 'luaharfbuzz'`
- Use `harfbuzz.shape` with the appropriate Lua types. See [example](https://github.com/deepakjois/luaharfbuzz/blob/master/examples/core_types.lua)

Quoting from [here](https://github.com/deepakjois/luaharfbuzz/issues/1):

> Note that the `harfbuzz._shape` is deprecated now. It is possible to do the same thing using the wrapped API types and the `harfbuzz.shape` method…Another thing is that the library should to be loaded using `require 'harfbuzz'` and not `require 'luaharfbuzz'` (as some of your sample code does). I will keep `harfbuzz._shape` around for a while, but I hope to remove it as soon as possible. So let me know once you have modified your code.

**Comment by michal-h21** [comment]
Done. New example:

For "ﺕﺍﺭیﺥ کے ﺺﻔﺣﺎﺗ ﻡیں پﺭﺍگ کﺍ پھﻻ ﺫکﺭ" string (from [Urdu wikipedia page about Prague](https://ur.wikipedia.org/wiki/پراگ), the output is following:

<img src="http://i.imgur.com/m1zRp9r.png" />

for some reason, the second word is wrong, the rest seem better (some minor spacing problems, maybe)

**Comment by deepakjois** [comment]
Beautiful :+1: !

Yes you are right, the second string is a bit off. I am very keen on diving into the LuaTeX side of things. But before that, there is a bit more work needed on _luaharfbuzz_.

It is already looking quite promising.

**Comment by michal-h21** [comment]
>
> Yes you are right, the second string is a bit off. I am very keen on
> diving into the LuaTeX side of things. But before that, there is a bit more
> work needed on *luaharfbuzz*.
>
I think that I can try to move this code to luatex-harfbuzz-shaper as soon
as we have language, direction and feature stuff working :)

> It is already looking quite promising.
>
> yeah, it goes better than I expected, especially x/y_shift stuff

**Comment by deepakjois** [comment]
On Fri, Dec 4, 2015 at 7:15 PM, Michal Hoftich <notifications@github.com>
wrote:

> I think that I can try to move this code to luatex-harfbuzz-shaper as soon
> as we have language, direction and feature stuff working :)
>

That is what I will be working on next. It is pretty trivial to integrate
language and direction. The feature stuff maybe a little bit more code, but
still don’t expect it to be a lot.

Maybe by sometime next week…

**Comment by deepakjois** [comment]
Btw, I noticed something odd with your Urdu input. The string you posted above seems to be using the codepoints for the isolated forms of many Arabic letters. 

Here is a demo (using the `hb-unicode-decode` tool in the Harfbuzz source tree):

First your string:
```
$> test/shaping/hb-unicode-decode "ﺕﺍﺭیﺥ کے ﺺﻔﺣﺎﺗ ﻡیں پﺭﺍگ کﺍ پھﻻ ﺫکﺭ"
U+FE95,U+FE8D,U+FEAD,U+06CC,U+FEA5,U+0020,U+06A9,U+06D2,U+0020,U+FEBA,U+FED4,U+FEA3,U+FE8E,U+FE97,U+0020,U+FEE1,U+06CC,U+06BA,U+0020,U+067E,U+FEAD,U+FE8D,U+06AF,U+0020,U+06A9,U+FE8D,U+0020,U+067E,U+06BE,U+FEFB,U+0020,U+FEAB,U+06A9,U+FEAD
```

Now, the corrected version, which I typed out on my own, copying the letters you pasted (if you look closely, you might notice a difference in shaping these characters as well. The isolated forms don’t join with each other under any circumstances, whereas the regular forms join as per rules of the Arabic script).

```
$> test/shaping/hb-unicode-decode "تاریخ کے صفحات میں پراگ کا پھلا ذکر"
U+062A,U+0627,U+0631,U+06CC,U+062E,U+0020,U+06A9,U+06D2,U+0020,U+0635,U+0641,U+062D,U+0627,U+062A,U+0020,U+0645,U+06CC,U+06BA,U+0020,U+067E,U+0631,U+0627,U+06AF,U+0020,U+06A9,U+0627,U+0020,U+067E,U+06BE,U+0644,U+0627,U+0020,U+0630,U+06A9,U+0631
```

For example, `U+FE95` (ARABIC LETTER TEH ISOLATED FORM) is the isolated form of `U+062A` (ARABIC LETTER TEH). You shouldn’t be using those.

Not sure what the problem is. Either there was an error in copy-pasting, or somebody is using a very broken keyboard to type this.

**Comment by deepakjois** [comment]
Language, direction, script and features are working as of deepak/luaharfbuzz@30f526f

**Comment by michal-h21** [comment]
It seems to be a copy and paste issue, I tried to copy your text and it seems to be the same as my original. I've tried it in Vim in terminal and in Gedit.

**Comment by michal-h21** [comment]
I've added support for LuaTeX's direction commands and fixed positioning issues: when `x_advance` differs from width, then it is kerning. Test text now:

![snimek z 2015-12-06 19 35 49](https://cloud.githubusercontent.com/assets/504800/11614888/ba9b9fe0-9c50-11e5-9d02-80c08d3b7b0f.png)
